# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '15.0'
use_frameworks!
target 'Escola de Formacao' do
	project 'Escola de Formacao.xcodeproj'
	pod 'Firebase/Messaging', '~> 10.23.0'
	pod 'Sodium', :commit => 'f67e6e0', :git => 'https://github.com/jedisct1/swift-sodium.git'
end

# BEGIN moodleapp-deployment-target-fix
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
# END moodleapp-deployment-target-fix
